version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - eKartar
      - app-tier
  dev-cache:
    image: bitnami/memcached:latest
    ports:
      - 11211:11211
    networks:
      - eKartar
      - app-tier
  dev-redis:
    image: redis:latest
    restart: always
    ports:
      - 6378:6379
    volumes:
      - cache:/data
networks:
  app-tier:
    driver: bridge
  eKartar:
volumes:
  cache:
    driver: local